[package]
name = "write_ahead_log"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.4"
memtable_element= {path= "../../help_structures/entry_element" }
bytes = "1.6.1"

[dev-dependencies]
serial_test = "3.1.1"