[package]
name = "sstable"
version = "0.1.0"
edition = "2021"

[dependencies]
entry_element={path="../../help_elements/entry_element"}
merkle_tree={path="../../tree_structures/merkle_tree"}
bloom_filter={path="../../probabilistic_structures/bloom_filter"}

[dev-dependencies]
serial_test = "3.1.1"